services:
  app:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8080
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
